#Select true or false (Default false)
init-spawn-setting: false
#coordinate and rotation (float value)
init-spawn-posX: '0.0'
init-spawn-posY: '0.0'
init-spawn-posZ: '0.0'
init-spawn-yaw: '0.0'
init-spawn-pitch: '0.0'
