name: HubServerUtility
version: '1.0-SNAPSHOT'
main: me.jiku.hubServerUtility.HubServerUtility
api-version: '1.21'
commands:
  hubserverutility:
    description: Show setting GUI
    permission: hubserverutility.op
    permission-message: You do not have permission to run this command
    aliases:
      - hsu
permissions:
  hubserverutility.op:
    description: This is for op permission
    default: op
